{{- if or .Values.mariadb.enabled .Values.externalDatabase.enabled .Values.postgresql.enabled }}
{{- if not .Values.externalDatabase.existingSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app.kubernetes.io/name: {{ include "nextcloud.name" . }}
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.mariadb.enabled }}
  {{- with .Values.mariadb.auth }}
  db-username: {{ .username | b64enc | quote }}
  db-password: {{ .password | b64enc | quote }}
  {{- end }}
  {{- else if .Values.postgresql.enabled }}
  {{- with .Values.postgresql.global.postgresql.auth }}
  db-username: {{ .username | b64enc | quote }}
  db-password: {{ .password | b64enc | quote }}
  {{- end }}
  {{- else }}
  {{- with .Values.externalDatabase }}
  db-username: {{ .user | b64enc | quote }}
  db-password: {{ .password | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
