{{- if .Values.prometheus.rules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nextcloud.name" . }}
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.prometheus.rules.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    {{- with .Values.prometheus.rules.defaults }}
    {{- if .enabled }}
    - name: {{ template "nextcloud.fullname" $ }}-Defaults
      rules:
        - alert: "nextcloud: not reachable"
          expr: 'avg(nextcloud_last_update_seconds{ {{ .filter }} }) without(endpoint,container,pod,instance) < 1'
          labels:
            severity: "critical"
            {{- with .labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{`
          annotations:
            summary: "Nextcloud in {{ $labels.namespace }} is not reachable by exporter"
          `}}
        - alert: "nextcloud: outdated version"
          expr: 'sum(nextcloud_system_update_available{ {{ .filter }} }) without(endpoint,container,pod,instance) > 0'
          labels:
            severity: "warning"
            {{- with .labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{`
          annotations:
            summary: "Nextcloud in {{ $labels.namespace }} is outdated"
          `}}
        - alert: "nextcloud: outdated apps"
          expr: 'sum(nextcloud_apps_updates_available_total{ {{ .filter }} }) without(endpoint,container,pod,instance) > 0'
          labels:
            severity: "warning"
            {{- with .labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{`
          annotations:
            summary: "Nextcloud in {{ $labels.namespace }} has {{ $value }} outdated Apps"
          `}}
    {{- end }}
    {{- end }}{{/* end-with metrics.rules.default */}}
    {{- if .Values.prometheus.rules.additionalRules }}
    - name: {{ template "nextcloud.fullname" . }}-Additional
      rules:
        {{- toYaml .Values.prometheus.rules.additionalRules | nindent 8 }}
    {{- end }}
{{- end }}

