nextcloud:
  defaultConfigs:
    imaginary.config.php: true
  configs:
    previews.config.php: |-
      <?php
      $CONFIG = array(
        'enabledPreviewProviders' => array(
          0 => 'OC\\Preview\\Imaginary',
          1 => 'OC\\Preview\\ImaginaryPDF',
        );

imaginary:
  enabled: true
