{{- if .Values.notifyPush.enabled }}
{{- with .Values.notifyPush.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nextcloud.fullname" $ }}-notify-push
  labels:
    app.kubernetes.io/name: {{ include "nextcloud.name" $ }}
    helm.sh/chart: {{ include "nextcloud.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/component: notify-push
    app.kubernetes.io/monitor: enabled
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .type }}
  {{- if eq .type "LoadBalancer" }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "nextcloud.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: notify-push
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: metrics
      port: 9100
      targetPort: metrics
{{- end }}
{{- end }}
