{{- if .Values.imaginary.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nextcloud.fullname" . }}-imaginary
  labels:
    app.kubernetes.io/name: {{ include "nextcloud.name" . }}
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: imaginary
    {{- with .Values.imaginary.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.imaginary.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.imaginary.service.type }}
  {{- with .Values.imaginary.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
    - name: http
      port: 80
      targetPort: http
      {{- with .Values.imaginary.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "nextcloud.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: imaginary
{{- end }}
